name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache remote deps
        run: deno cache server.ts

      - name: Format check
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Type check
        run: deno check server.ts

      # If you add tests later, they'll run here (passes with 0 tests now)
      - name: Test
        run: deno test -A
